# Generated by Django 5.0.1 on 2024-02-03 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('ArchiveID', models.AutoField(primary_key=True, serialize=False)),
                ('OriginalTable', models.CharField(max_length=50)),
                ('OriginalID', models.IntegerField()),
                ('ArchiveDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('MeatID', models.AutoField(primary_key=True, serialize=False)),
                ('MeatType', models.CharField(max_length=50)),
                ('PricePerKg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('PurchaseID', models.AutoField(primary_key=True, serialize=False)),
                ('PurchaseDate', models.DateField()),
                ('QuantityKg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('MeatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.meat')),
            ],
        ),
    ]
